spring:
  application:
    name: audit-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.default_schema: app

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/audit-service
    username: postgres
    password: postgres

  jackson:
    property-naming-strategy: SNAKE_CASE

  config:
    import: confidential.yml

logging:
  level:
    org:
      hibernate:
        SQL:
          DEBUG
        orm:
          jdbc:
            bind:
              Trace

server:
  port: 8080

app:
  user-url: http://user-service:8080/users
