# Оправка через mail.ru

spring:
  mail:
    host: smtp.mail.ru
    port: 465
    username: ***@mail.ru
    password: ...
    properties:
      "mail.smtp.ssl.enable": true
      mail:
        encoding: UTF-8
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: ITAcademy
  user: User
  system: System




